# Generated by Django 3.2 on 2021-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='homepage',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
